### ISSUE TITLE
Support Server.MapPath

### ISSUE THREAD

**Issue by KathleenDollard** [csharpfritz/WebFormsTest#21]
The empty server that's used doesn't support MapPath. Its not clear how to let it know the base path so that it can properly concatenate.

**Comment by csharpfritz** [comment]
Thinking about it:  WebApplicationProxy knows where the source code is on disk and instantiates Application.  Perhaps we can do some fancy re-routing when Server.MapPath is called to look at the folder information in WebApplicationProxy

**Comment by csharpfritz** [comment]
I'm seeing an ugly problem with this because the MapPath method routes through the Host object and queries IIS to perform the mapping.

Would it suffice if we wrote a hack that chopped the web root folder and called Path.Combine to join the physical path with the virtual path?

**Comment by KathleenDollard** [comment]
It would for me.

**Comment by csharpfritz** [comment]
Lets run with that as a short-term "YAGNI" solution

Jeff

**Comment by csharpfritz** [comment]
Added simple join support for Server.MapPath

The TestServer object must be added to any context under test in order to support this.  We should look at making the construction of HttpContext for testing much easier, and include the TestServer
