### ISSUE TITLE
Two Session issues

### ISSUE THREAD

**Issue by KathleenDollard** [csharpfritz/WebFormsTest#26]
I have code that needs Session that is not in the Page hierarchy. Currently up, the non-page code that is looking for Session is in Global.asax, which has a static method that gets the SessionId for use in a dictionary of SessionKeys (SessionId/Session for reasons not yet clear) (for the record, I'm just trying to unravel old code). 

1) Since the Context and Session are on the base page, this doesn't work. I can create a singleton or something, but I thought discussing a consistent way to handle this might be worthwhile. 

2) HttpSessionStateBase doesn't have a SessionId property

**Comment by csharpfritz** [comment]
Can you share some sample code that demonstrates the non-page code looking
for session?

This sounds like it feeds into the requirement of issue #13 - mirroring the
mocked HttpContext into the HttpContext.Current, but I need more
information about your use case.

Jeff

**Comment by csharpfritz** [comment]
HttpSessionStateBase does have a SessionID property:
http://referencesource.microsoft.com/#System.Web/Abstractions/HttpSessionStateBase.cs,82

It's get only, but its there.

**Comment by csharpfritz** [comment]
Fixed and unit tested with 0a8d0aa058dea3c77b7b06888a7ce2778ef350cd

WebApplicationProxy now has a GetSession method that will deliver a new and empty session with a fresh sessionId.  Add the session to your context by passing ctx => AddSession(myNewSession) in to WebApplicationProxy.GetPageByLocation.
