### ISSUE TITLE
Feature: Handle AutoEventWireup

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/WebFormsTest#4]
Need to handle magic event handler signatures that get triggered like
`protected void Page_Load(object sender, EventArgs args)`

**Comment by csharpfritz** [comment]
After reviewing http://referencesource.microsoft.com this is a TOUGH feature to add.  The events are connected using IL emit statements.  It can be done, but will take a lot of code.

Need to analyze the ASPX that goes with a code-behind to check this configuration option is set before wiring up

**Comment by KathleenDollard** [comment]
We use this feature, so this is critical to us. 

Is the implementation of this dependent on the implementation of the event pipeline? More comments there.
