### ISSUE TITLE
Default WebForms (VS 2015) not Testable

### ISSUE THREAD

**Issue by KathleenDollard** [csharpfritz/WebFormsTest#40]
Default WebForms with very few changes and a simple test resulted in this error:

System.UnauthorizedAccessException was unhandled
Message: An unhandled exception of type 'System.UnauthorizedAccessException' occurred in mscorlib.dll
Additional information: Access to the path 'C:\$RECYCLE.BIN\S-1-5-18' is denied.

**Comment by csharpfritz** [comment]
We're missing support for Bundles and FriendlyUrls.
- [x] Support Bundles
- [x] Support FriendlyUrls

**Comment by csharpfritz** [comment]
I think that last commit into dev completes this
