### ISSUE TITLE
Please release latest code to Nuget gallery

### ISSUE THREAD

**Issue by DannyMeister** [csharpfritz/WebFormsTest#56]
Using latest compiled code, I can get this project to work.  But the 1.3 and 1.4 beta versions on the nuget gallery do not have the regex from PR #52 so it bombs while trying to determine the location.

**Comment by csharpfritz** [comment]
Sure... I'll put this together and ship today

**Comment by csharpfritz** [comment]
Just published 1.4.0

**Comment by DannyMeister** [comment]
@csharpfritz Our project currently targets .NET 4.7.1 so can't include your 1.4.0 package which you have updated to target 4.8.  We can't make an immediate pivot as it will require all the downstream teams responsible for test and production environments to get there first.  Given that webforms projects are generally maintenance mode legacy stuff, it will be hard for folks to get buy in on prioritizing an upgrade.  So maybe it's best to keep the lowest possible target?
