### ISSUE TITLE
Bug: MockPostData does not create child controls

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/WebFormsTest#7]
MockPostData calls EnsureChildControls but does not create the control tree.

Added unit tests to test with a Static ClientID on a textbox control

**Comment by csharpfritz** [comment]
To build the control tree, the test harness needs to be able to load the ASPX / ASCX source.

**Comment by csharpfritz** [comment]
Added static WebRootFolder property to the TestablePage class to allow the unit-test harness to locate the ASPX / ASCX template files

**Comment by csharpfritz** [comment]
If I'm reading things right...  requests are routed through a PageParser to load + parse ASPX content then compile in the code-behind.  This will change our approach to building the harness

**Comment by KathleenDollard** [comment]
Ah, the heart the matter! :-)

I suggest this simple scenario be included in the tests

WebForms with two buttons. One (A) is disabled when form opens. 
- Test 1 confirms that after Page_Load A button is disabled and B button is enabled

Clicking either button disables it and enables the other button
- Test 2 confirms that after the event handler for A fires, it is disabled and B is enabled
- Test 3 confirms that after the event handler for B fires, it is disabled and A is enabled

Test 1 is the big lift you're discussing here - hydrate to default. 

Tests 2 and 3 will also need a pattern for setting values in the test's Arrange section. 

So not only does the hydration needs to occur, the test needs to hydrate the form, it needs to allow arrange code to run (possibly in a lambda) after hydration.

**Comment by csharpfritz** [comment]
I've got the control tree rebuilt in the WebFormsTest@af61ba1c33c7f80b4f17cfb7aeddd3596d943f48 commit.  Before tagging and bagging this feature, I'd like to put together test pages and unit tests to verify that your Test 1, 2, and 3 are all possible.

Check the Fritz.WebFormsTest.Test.Postback_Simple_Fixture.TextboxAddedToControlSet text for an example of something VERY close to Test 1.  This test shows that a textbox was loaded and the default text was set in the box that was defined in the ASPX file.

**Comment by csharpfritz** [comment]
... and WOW, even AppVeyor precompiled the ASPX and delivered the content to the WebFormsTest harness properly.

I am VERY encouraged by the progress on this feature.

**Comment by csharpfritz** [comment]
Completed rehydrating the controls with commit: dev@eb35e1fe8dbd6a7a20e66c50c5fba537d6606441

**Comment by csharpfritz** [comment]
Separating Test 2 and 3 into an issue report (and thus some unit tests) for Milestone 0.6 - Control events
