### ISSUE TITLE
Globally accessible 'InTestMode' property

### ISSUE THREAD

**Issue by KathleenDollard** [csharpfritz/WebFormsTest#9]
I'm not quite sure how this would work, and how it would solve and/or not create the parallel testing issues in issue #8, but here's the problem...

The page can have a IsInTestMode property. But how do you get to this property if code is called that is not on the page that also needs to have test/non-test behavior. Because this is WebForms and DI is unlikely, explicit mocking may sometimes be the best option (calls to instantiate different property values for things like repos explicitly in the constructor). There isn't currently a way for non-page code to know whether it's currently in test or production mode.

**Comment by csharpfritz** [comment]
This feels like a boolean that could be added to HttpContext.Items.  Not sure about the timing of setting that key, perhaps on HttpContext.set?

**Comment by csharpfritz** [comment]
Added to fake HttpContext.Current: Items["IsInTest"] = true at dev@4c3dc65f7c5f8002f5a1191cc906184b1836c042
